### ISSUE TITLE
Open dialog when click on input

### ISSUE THREAD

**Issue by ahmadmrj** [karianpour/react-hichestan-datetimepicker#7]
I want dialog opened when user clicks on input Not just calendar icon. 
I didn't find any option. Is there any way to open dialog with "onClick" option?

**Comment by karianpour** [comment]
@ahmadmrj sure, that make sense, I will add the option and let you know in the next release.

**Comment by karianpour** [comment]
new boolean prop is added for this purpose, `autoPop`.
