### ISSUE TITLE
Different selected time and output time in jalali mode

### ISSUE THREAD

**Issue by yousefshakoury** [karianpour/react-hichestan-datetimepicker#9]
The first thanks for great component!
What my selected time and output time they are different!!!
![image](https://user-images.githubusercontent.com/13915152/98955847-a56eae80-2514-11eb-8b00-6c5f768e30d6.png)
As you see my selected time is "18:23" but output time is "14:53", that I think it use timezone for that!
How I can to fix it to output "18:23" same as input time!
Thanks!

**Comment by karianpour** [comment]
Thanks for using the component. The problem you mention is the timezone. But it is intentionally that way.

18:23+04:30 === 14:53Z

if you send it to the backend this should be even better if you send it a UTC. But if you really need to do that, there is no way in pure JS unless you try with `Date.toLocalString(, option)` find the desired option for your need.
